spring.application.name=dailyreport
spring.datasource.url=jdbc:postgresql://localhost:5432/daily_report_db
spring.datasource.username=postgres
spring.datasource.password=1998hika
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
